applications/contact/urls.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.urls import path, include

from django.contrib.auth.decorators import login_required

from .views import ContactView

urlpatterns = [
    path('', (ContactView.as_view()), name='contact'),
]

devops/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.blogs.urls')),
    path('scribblings/', include('applications.gallery.urls')),
    path('contact-us/', include('applications.contact.urls')),
    path('accounts/', include('applications.accounts.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/contact/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.mail import send_mail
from django.conf import settings


class Contact(models.Model):
    first_name = models.CharField(max_length=235)
    last_name = models.CharField(max_length=235)
    subject = models.CharField(max_length=235)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'Contact'
        verbose_name_plural = 'Contacts'


@receiver(post_save, sender=Contact)
def contact_profile(sender, instance, created, **kwargs):
    # send_mail('New Book Request', message, 'hello.laaddu@gmail.com', [instance.owner_user.email], fail_silently=False)
    pass

applications/contact/forms.py
from django import forms

from .models import Contact


class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = ('first_name', 'last_name', 'subject', 'email', 'message')

applications/contact/views.py
import json

from django.views import generic
from django.conf import settings
from django.template.loader import get_template
from django.core.mail import EmailMultiAlternatives
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.http import JsonResponse

from .forms import ContactForm


class ContactView(generic.FormView):

    form_class = ContactForm
    template_name = "contact/contact_page.html"

    def form_valid(self, form):
        text_template = get_template('email_templates/contact_message.html')
        user_name = form.cleaned_data['first_name'] + form.cleaned_data['last_name']
        subject = 'Contact request from {}'.format(user_name)
        context = {'formentry': self.request.POST}
        text_content = text_template.render(context)
        from_email = settings.EMAIL_HOST_USER
        to = [settings.EMIAL_HOST_ADMIN]
        msg = EmailMultiAlternatives(subject, text_content, from_email, to)
        msg.attach_alternative(text_content, "text/html")
        msg.send()
        form.save()
        return JsonResponse({'status':'success'})

    def form_invalid(self, form):
        return HttpResponse(json.dumps({'result': {'status': 'form_error', 'errors': form.errors}}),
                            content_type='application/json')

    def get_success_url(self):
        return '/'

templates/contact/contact_page.html
{% extends 'base.html' %}
{% block extra_css %}
<style>
	.error{
		color: red;
	}
</style>
{% endblock %}
{% block title %}Contact{% endblock %}
{% block content %}


		<section id="home" class="video-hero" style="height: 100vh; background-image: url(/static/images/cover_img_2.jpg);  background-size:cover; background-position: center center;background-attachment:fixed;" data-section="home">
		<div class="overlay" style="height: 100vh;"></div>
			<div class="display-t text-center">
				<div class="display-tc">
					<div class="container">
						<div class="col-md-10 col-md-offset-1">
							<div class="animate-box">
								<h2>Contact Us</h2>
								<p class="breadcrumbs"><span><a href="/">Home</a></span> <span>Contact</span></p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>

		<div id="colorlib-contact">
			<div class="container">
				<div class="row">
					<div class="col-lg-12 col-md-12  animate-box">
						<h2>Get In Touch</h2>
						<!--<form action="#">-->
							<form id="contactform" action="" method="post">
								{% csrf_token %}
							<div class="row form-group">
								<div class="col-md-6">
									<input type="text" id="id_first_name" onkeyup="removeError('first_name')" name="first_name" class="form-control" placeholder="Your firstname">
									<span id="first_name" class="error"></span>
								</div>
								<div class="col-md-6">
									<input type="text" id="id_last_name" name="last_name" onkeyup="removeError('last_name)" class="form-control" placeholder="Your lastname">
									<span id="last_name" class="error"></span>
								</div>
							</div>

							<div class="row form-group">
								<div class="col-md-12">
									<input type="text" id="id_email" name="email" onkeyup="removeError('email')" class="form-control" placeholder="Your email address">
									<span id="email" class="error"></span>
								</div>
							</div>

							<div class="row form-group">
								<div class="col-md-12">
									<input type="text" id="id_subject" name="subject" onkeyup="removeError('subject')" class="form-control" placeholder="Your subject of this message">
									<span id="subject" class="error"></span>
								</div>
							</div>

							<div class="row form-group">
								<div class="col-md-12">
									<textarea name="message" id="id_message" cols="30" onkeyup="removeError('message')" rows="10" class="form-control" placeholder="Say something about us"></textarea>
									<span id="message" class="error"></span>
								</div>
							</div>
							<div class="form-group">
								<button id="btn-submit" class="btn btn-primary"> Send Message </button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
{% endblock %}
{% block extra_js %}

<script>

function removeError(id){
	document.getElementById(id).innerHTML = "";
}

var count = 0;
$('#btn-submit').click(function() {
	<!--document.getElementById("success-message").innerHTML = "";-->
	var data = $('#contactform').serialize();
	var url = "{% url 'contact' %}"
	$('.error').html("");
    $('#successful').html("");
    document.getElementById("btn-submit").innerHTML = "SENDING...";
	$.ajax({
		type: 'POST',
		url: url,
		data: data,
		cache : false,
		processData: false,

		success: function (response) {
			if (response.status == 'success') {
				$('.error').remove();
				document.getElementById("btn-submit").innerHTML = "Send Message";
				document.getElementById("success-message").innerHTML = "Message Sent Successfully";
				$('#contactform')[0].reset();
			}
			else if (response.result.status == 'form_error') {
				document.getElementById("btn-submit").innerHTML = "Send Message";

				$("#contactform :input:not(input[type='hidden'],input[type='submit'])").each(function () {
					var current = $(this).parent();
					var current_name = $(this).attr('name');
					$.each(response.result.errors, function (index, value) {
						if (current_name == index) {
							$('#'+current_name).html(value);
						}
					});
				});
			}
		},
		error: function(error){}
	});
	return false;
});
</script>
{% endblock %}